from datetime import timedelta

# Generated by CodiumAI

from app.utils import readable_timedelta


class TestReadableTimedelta:

    #  Returns a string in the format "Xd Xh Xm Xs" for a
    #  timedelta object with non-zero days, hours, minutes and seconds.
    def test_non_zero_days_hours_minutes_seconds(self):
        duration = timedelta(days=2, hours=3, minutes=4, seconds=5)
        assert readable_timedelta(duration) == '2d 3h 4m 5s'

    #  Returns a string in the format "Xh Xm Xs" for a timedelta
    #  object with non-zero hours, minutes and seconds, but zero days.
    def test_zero_days_non_zero_hours_minutes_seconds(self):
        duration = timedelta(hours=3, minutes=4, seconds=5)
        assert readable_timedelta(duration) == '3h 4m 5s'

    #  Returns a string in the format "Xm Xs" for a timedelta object with non-zero
    #  minutes and seconds, but zero days and hours.
    def test_zero_days_zero_hours_non_zero_minutes_seconds(self):
        duration = timedelta(minutes=4, seconds=5)
        assert readable_timedelta(duration) == '4m 5s'

    #  Returns a string in the format "Xd Xh Xm Xs" for a timedelta object with maximum
    #  possible values for days, hours, minutes and seconds.
    def test_maximum_values(self):
        duration = timedelta(days=999999999, hours=23, minutes=59, seconds=59)
        assert readable_timedelta(duration) == '999999999d 23h 59m 59s'

    #  Returns a string in the format "Xh Xm Xs" for a timedelta object with maximum possible
    #  values for hours, minutes and seconds, but zero days.
    def test_maximum_values_zero_days(self):
        duration = timedelta(hours=23, minutes=59, seconds=59)
        assert readable_timedelta(duration) == '23h 59m 59s'
